config/routes.rb
Typekata::Application.routes.draw do
  root 'katas#index'

  resources :katas, only: [:index, :new, :create, :show]

  get "about_us", to: "pages#about_us"

  

end

app/models/kata.rb
class Kata < ActiveRecord::Base
  validates :name, presence: true
  validates :text, presence: true
  validates :language, presence: true

  belongs_to :language
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :kata
end

app/controllers/katas_controller.rb
class KatasController < ApplicationController
  def index
    @katas = Kata.all
  end

  def new
    @kata = Kata.new
    @languages = Language.all
  end

  def create
    @kata = Kata.create(params[:kata])
  end

  def show
    @kata = Kata.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us

  end
end

app/views/javascripts/_google_analytics_tag.haml
:plain
  <!-- Google Analytics -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '#{Secrets['GOOGLE_ANALYTICS_TRACKING_ID']}', 'typekata.com');
    ga('send', 'pageview');

  </script>

app/views/katas/new.haml
.container
  = simple_form_for :kata  do |f|
    .form-group
      = f.input :name, input_html: { class: "form-control" }
      = f.input :language_id

    .form-group
      = f.label "What's your Kata all about?"
      = f.text_area :description, { class: "form-control" }

    .form-group
      = f.label "Code:"
      = f.text_area :text, {placeholder: "Your code goes here!", class: "form-control" }

    .form-group
      = f.button :submit, class: "btn btn-primary"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>TypeKata</title>
<meta name="description" content="Type faster. Type smarter. Become a better developer.">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<!-- Latest compiled and minified CSS for bootstrap-->
<link href="https://netdna.bootstrapcdn.com/bootstrap/3.0.0-rc2/css/bootstrap.min.css" rel="stylesheet">
<link href="/assets/fonts.css" rel="stylesheet">
<link href="/assets/style.css" rel="stylesheet">
<link href="/assets/prism.css" rel="stylesheet">

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://code.jquery.com/jquery.js"></script>
  <!-- Latest compiled and minified JavaScript for bootstrap-->
  <script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.0-rc2/js/bootstrap.min.js"></script>
  <script src="/assets/prism.js"></script>

  <!-- Custom css -->
  <%= stylesheet_link_tag "application" %>

  <!-- Custom javascript -->
  <%= javascript_include_tag "application" %>
</head>
<body>
  <!-- NAVBAR -->
  <nav class="navbar" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "TypeKata", root_path, class: "navbar-brand brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Katas", root_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About us", about_us_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <%= yield %>
  <%= render partial: "javascripts/google_analytics_tag" %>
</body>
</html>

app/views/pages/about_us.haml
.container
  %h1
    TypeKata is where developers learn to type faster.

  %p With TypeKata, you can practice your typing skills on small bits of code and see your typing speed increase as you practice.

  %h2 What's a Kata?
  %p A Kata is an exercise performed repeatedly to achieve mastery of a skill.

  %h2 How is typing speed measured?
  %p
    Typing speed is measured in
    %b Words Per Minute
    (WPM), where a word is considered to be 5 characters long on average.

  %h2 Where does TypeKata come from?
  %p
    TypeKata is an open source project maintained by Victor and Johan.
    %a{href: "http://github.com/victormours/typekata"}
      Find us on github!